Neos:
  Flow:
    mvc:
      routes:
        'Flownative.Canto':
          position: 'start'

    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'Flownative.Canto:AuthorizationController':
                pattern: 'ControllerObjectName'
                patternOptions:
                  controllerObjectNamePattern: 'Flownative\Canto\Controller\AuthorizationController'

  Media:
    assetSources:
      'flownative-canto':
        assetSource: 'Flownative\Canto\AssetSource\CantoAssetSource'
        assetSourceOptions:
          iconPath: 'resource://Flownative.Canto/Public/Icons/Canto-Logo-White.svg'
          description: 'Assets in Canto Digital Asset Management'
          appId: '%env:FLOWNATIVE_CANTO_OAUTH_APP_ID%'
          appSecret: '%env:FLOWNATIVE_CANTO_OAUTH_APP_SECRET%'
          apiBaseUri: '%env:FLOWNATIVE_CANTO_API_BASE_URI%'

  Neos:
    modules:
      management:
        submodules:
          canto:
            controller: 'Flownative\Canto\Controller\CantoController'
            label: 'Canto'
            description: 'Flownative.Canto:Main:moduleDescription'
            icon: 'fas fa-photo-video'
            privilegeTarget: 'Flownative.Canto:ManageConnection'
